/**
 * SmartSuggestions.jsx — Fully dynamic, document-driven topic explorer.
 *
 * Topics are generated by the backend Suggestion Agent (GROQ_QWEN) from
 * the user's actual uploaded document chunks.  No static topics exist —
 * if no documents are uploaded the component shows an upload prompt.
 */

import { useState } from 'react'
import { FolderOpen, Sparkles } from 'lucide-react'

export default function SmartSuggestions({ onPromptClick, disabled, dynamicTopics = [] }) {
  const [activeId, setActiveId] = useState(null)

  const activeTopic = dynamicTopics.find(t => t.label === activeId)

  function toggleTopic(label) {
    setActiveId(prev => (prev === label ? null : label))
  }

  // ── Empty state: no docs uploaded yet ───────────────────────────────────────
  if (dynamicTopics.length === 0) {
    return (
      <div className="ss-root">
        <div className="ss-heading">
          <span className="ss-heading-icon"><Sparkles size={15} /></span>
          <span>Smart Suggestions</span>
          <span className="ss-heading-sub">Upload documents to unlock personalised questions</span>
        </div>
        <div className="ss-empty">
          <div className="ss-empty-icon"><FolderOpen size={22} strokeWidth={1.5} /></div>
          <div className="ss-empty-text">
            Once you upload a document, the AI will analyse it and suggest
            specific questions you can ask — tailored to your content.
          </div>
        </div>
      </div>
    )
  }

  // ── Topic chips + expanded prompts ───────────────────────────────────────────
  return (
    <div className="ss-root">
      <div className="ss-heading">
        <span className="ss-heading-icon"><Sparkles size={15} /></span>
        <span>Smart Suggestions</span>
        <span className="ss-heading-sub">Topics discovered from your documents — click to explore</span>
      </div>

      {/* Topic chips */}
      <div className="ss-chips">
        {dynamicTopics.map(topic => {
          const isActive = activeId === topic.label
          const glow = topic.color + '40'   // 25% opacity glow from hex color
          return (
            <button
              key={topic.label}
              className={`ss-chip ${isActive ? 'ss-chip--active' : ''}`}
              style={isActive ? {
                borderColor: topic.color,
                color:        topic.color,
                boxShadow:   `0 0 16px ${glow}`,
                background:   glow,
              } : {}}
              onClick={() => toggleTopic(topic.label)}
              disabled={disabled}
            >
              <span>{topic.icon}</span>
              <span>{topic.label}</span>
            </button>
          )
        })}
      </div>

      {/* Expanded prompts */}
      {activeTopic && (
        <div
          className="ss-prompts"
          style={{ borderColor: activeTopic.color + '44' }}
          key={activeTopic.label}
        >
          <div className="ss-prompts-title" style={{ color: activeTopic.color }}>
            {activeTopic.icon}&nbsp; {activeTopic.label} — click any question to ask it
          </div>
          <div className="ss-prompt-list">
            {activeTopic.prompts.map((p, i) => (
              <button
                key={i}
                className="ss-prompt-btn"
                style={{ animationDelay: `${i * 0.06}s` }}
                onClick={() => {
                  onPromptClick(p)
                  setActiveId(null)
                }}
                disabled={disabled}
              >
                <span className="ss-prompt-arrow">→</span>
                <span>{p}</span>
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

// Export for Playbook panel to list topics
export { }
